# Generated by Django 5.2.7 on 2025-10-26 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlanetarySystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название планеты')),
                ('description', models.TextField(verbose_name='Описание')),
                ('photo', models.ImageField(upload_to='planet_photo/', verbose_name='Фото')),
                ('aged', models.FloatField(verbose_name='Возраст в миллиардах лет')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('planetary_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planets', to='astro_objects.planetarysystem', verbose_name='Планетарная система')),
            ],
            options={
                'verbose_name': 'Планета',
                'verbose_name_plural': 'Планеты',
            },
        ),
        migrations.CreateModel(
            name='Star',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название звезды')),
                ('description', models.TextField(verbose_name='Описание')),
                ('photo', models.ImageField(upload_to='star_photo/', verbose_name='Фото')),
                ('status', models.TextField(verbose_name='Статус')),
                ('aged', models.FloatField(verbose_name='Возраст в миллиардах лет')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('planetary_system', models.ManyToManyField(related_name='star', to='astro_objects.planetarysystem', verbose_name='Создаваемая планетарная система')),
            ],
            options={
                'verbose_name': 'Звезда',
                'verbose_name_plural': 'Звезды',
            },
        ),
    ]
