# Generated by Django 5.2.7 on 2025-11-08 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astro_objects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='star',
            name='planetary_system',
        ),
        migrations.AddField(
            model_name='star',
            name='planetary_systems',
            field=models.ManyToManyField(related_name='stars', to='astro_objects.planetarysystem', verbose_name='Создаваемые планетарные системы'),
        ),
    ]
