# Generated by Django 5.2.7 on 2025-11-08 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astro_objects', '0002_remove_star_planetary_system_star_planetary_systems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='star',
            name='planetary_systems',
            field=models.ManyToManyField(related_name='stars', to='astro_objects.planetarysystem', verbose_name='Планетарные системы'),
        ),
    ]
