# Generated by Django 5.2.7 on 2025-11-08 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('astro_objects', '0003_alter_star_planetary_systems'),
    ]

    operations = [
        migrations.RenameField(
            model_name='star',
            old_name='planetary_systems',
            new_name='planetary_system',
        ),
    ]
